name: Generate Tech Adventure Map

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the adventure-map.svg
      - name: Generate Tech Adventure Map
        run: |
          echo "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 500 500'>
          <style>
            .text { font: bold 24px sans-serif; fill: white; }
          </style>
          <rect width='100%' height='100%' fill='black'/>
          <text x='50%' y='50%' class='text' dominant-baseline='middle' text-anchor='middle'>Welcome to Your Tech Adventure Map</text>
          <text x='50%' y='60%' class='text' dominant-baseline='middle' text-anchor='middle'>Unlock new levels by learning and building!</text>
          </svg>" > adventure-map.svg

      # Push the generated SVG to the output branch
      - name: Push Tech Adventure Map to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
